sudo: required

language: python

services:
  - docker

before_script:
  - python --version
  - docker version
  - docker ps -a
  - docker build -t clarencep/lap7:$TRAVIS_BRANCH .
  - docker images
  - docker ps -a

script:
  - for tag in latest ubuntu centos6 centos7; do docker run -it --rm clarencep/lap7:$tag sh -c "php -v && php -m && cat /etc/*release*"; done;
