sudo: required

language: python

services:
  - docker

before_script:
  - python --version
  - docker version
  - docker ps -a
  - docker build -t clarencep/lap7 .
  - docker images
  - docker ps -a

script:
  - docker run -d -p 8080:80 clarencep/lap7
  - curl -v --retry 5 --retry-delay 2 http://localhost:8080/
